-- Sample catalogue. Generated from lib/demo-data.ts — edit there and re-run scripts/generate-seed.ts.
insert into public.categories (slug, name, tone, sort) values
  ('tailoring', 'Tailoring', 'linear-gradient(135deg,#D9DFEE,#8FA0C8)', 0),
  ('beautician', 'Beautician Certification', 'linear-gradient(135deg,#F1D3E3,#CF86B0)', 1),
  ('nail-art', 'Nail Art', 'linear-gradient(135deg,#F6DDE9,#DE93BC)', 2),
  ('mehandi', 'Mehandi Design', 'linear-gradient(135deg,#EFDDAE,#C3A04F)', 3),
  ('embroidery', 'Embroidery', 'linear-gradient(135deg,#E3D8EF,#9C7DC2)', 4),
  ('saree-draping', 'Saree Draping', 'linear-gradient(135deg,#DDE9D6,#8DAF7E)', 5)
on conflict do nothing;

insert into public.faculty (id, name, initials, specialty, years, students, bio) values
  ('f-lakshmi', 'Lakshmi V.', 'LV', 'Master Tailor', 15, 2100, 'Runs a boutique in Jayanagar and has trained over 2,100 tailors in pattern drafting and bridal blouse work.'),
  ('f-deepa', 'Deepa K.', 'DK', 'Beautician', 12, 1500, 'Certified cosmetologist and bridal artist. Leads the beautician certification track.'),
  ('f-kavya', 'Kavya S.', 'KS', 'Nail art', 8, 900, 'Studio owner specialising in gel, chrome and hand-painted nail art.'),
  ('f-anjali', 'Anjali R.', 'AR', 'Mehandi', 10, 1200, 'Bridal mehandi artist who takes 60+ weddings a season.'),
  ('f-radha', 'Radha N.', 'RN', 'Embroidery', 11, 640, 'Aari and maggam work specialist for bridal blouses and lehengas.'),
  ('f-meera', 'Meera T.', 'MT', 'Saree draping', 9, 760, 'Drapes for weddings and shoots in 12+ regional styles.')
on conflict do nothing;

insert into public.courses (id, slug, title, category_slug, level, duration_days, price, mode, language, rating, ratings_count, students, summary, description, outcomes, modules, faculty_id, featured) values
  ('c-1', 'tailoring-master-pro-180-days', 'Tailoring Master Pro (180 Days)', 'tailoring', 'Pro Master', 180, 49999, 'Online & offline', 'English, Hindi, Kannada', 4.5, 80, 300, '180-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Module 1 — Fundamentals","days":45},{"title":"Module 2 — Core Techniques","days":54},{"title":"Module 3 — Applied Practice","days":45},{"title":"Module 4 — Refinement & Finishing","days":22},{"title":"Module 5 — Business & Portfolio Skills","days":14}]'::jsonb, 'f-lakshmi', false),
  ('c-2', 'tailoring-advanced-master-class-90-days', 'Tailoring Advanced Master Class (90 Days)', 'tailoring', 'Advanced', 90, 29999, 'Online & offline', 'English, Hindi, Kannada', 4.7, 133, 497, '90-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Module 1 — Fundamentals","days":23},{"title":"Module 2 — Core Techniques","days":27},{"title":"Module 3 — Applied Practice","days":23},{"title":"Module 4 — Refinement & Finishing","days":11},{"title":"Module 5 — Business & Portfolio Skills","days":6}]'::jsonb, 'f-lakshmi', false),
  ('c-3', 'tailoring-pro-class-60-days', 'Tailoring Pro Class (60 Days)', 'tailoring', 'Advanced', 60, 19999, 'Online & offline', 'English, Hindi, Kannada', 4.9, 186, 694, '60-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Module 1 — Fundamentals","days":15},{"title":"Module 2 — Core Techniques","days":18},{"title":"Module 3 — Applied Practice","days":15},{"title":"Module 4 — Refinement & Finishing","days":7},{"title":"Module 5 — Business & Portfolio Skills","days":5}]'::jsonb, 'f-lakshmi', false),
  ('c-4', 'tailoring-master-class-30-days', 'Tailoring Master Class (30 Days)', 'tailoring', 'Master', 30, 8999, 'Online & offline', 'English, Hindi, Kannada', 4.6, 239, 891, '30-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Module 1 — Fundamentals","days":8},{"title":"Module 2 — Core Techniques","days":9},{"title":"Module 3 — Applied Practice","days":8},{"title":"Module 4 — Refinement & Finishing","days":4},{"title":"Module 5 — Business & Portfolio Skills","days":1}]'::jsonb, 'f-lakshmi', false),
  ('c-5', 'tailoring-foundation-course-14-days', 'Tailoring Foundation Course (14 Days)', 'tailoring', 'Foundation', 14, 1999, 'Online', 'English, Hindi, Kannada', 4.8, 292, 1088, '14-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Module 1 — Fundamentals","days":4},{"title":"Module 2 — Core Techniques","days":4},{"title":"Module 3 — Applied Practice","days":4},{"title":"Module 4 — Refinement & Finishing","days":2}]'::jsonb, 'f-lakshmi', false),
  ('c-6', 'tailoring-basic-course-3-days', 'Tailoring Basic Course (3 Days)', 'tailoring', 'Basic', 3, 999, 'Online', 'English, Hindi, Kannada', 4.5, 345, 1285, '3-day tailoring programme with hands-on practice and an industry-recognised certificate.', 'A structured tailoring programme covering hand and machine stitching fundamentals, pattern drafting for blouses, salwars & dresses, fitting, alteration & garment finishing. Every module has practice assignments graded by faculty.', array['Hand and machine stitching fundamentals','Pattern drafting for blouses, salwars & dresses','Fitting, alteration & garment finishing','Fabric selection and cutting techniques','Boutique pricing & order management','Portfolio-building for client work']::text[], '[{"title":"Tools, materials & safety","days":1},{"title":"Core techniques","days":1},{"title":"Practice piece & review","days":1}]'::jsonb, 'f-lakshmi', false),
  ('c-7', 'beautician-master-pro-180-days', 'Beautician Master Pro (180 Days)', 'beautician', 'Pro Master', 180, 59999, 'Online & offline', 'English, Hindi, Kannada', 4.7, 98, 1482, '180-day beautician certification programme with hands-on practice and an industry-recognised certificate.', 'A structured beautician certification programme covering skin analysis and facial treatments, threading, waxing and hygiene standards, party and hd makeup. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Skin analysis and facial treatments','Threading, waxing and hygiene standards','Party and HD makeup','Hair styling basics','Client consultation & aftercare','Pricing and running a home salon']::text[], '[{"title":"Module 1 — Fundamentals","days":45},{"title":"Module 2 — Core Techniques","days":54},{"title":"Module 3 — Applied Practice","days":45},{"title":"Module 4 — Refinement & Finishing","days":22},{"title":"Module 5 — Business & Portfolio Skills","days":14}]'::jsonb, 'f-deepa', false),
  ('c-8', 'beautician-master-expert-90-days', 'Beautician Master Expert (90 Days)', 'beautician', 'Advanced', 90, 39999, 'Online & offline', 'English, Hindi, Kannada', 4.9, 151, 1679, '90-day beautician certification programme with hands-on practice and an industry-recognised certificate.', 'A structured beautician certification programme covering skin analysis and facial treatments, threading, waxing and hygiene standards, party and hd makeup. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Skin analysis and facial treatments','Threading, waxing and hygiene standards','Party and HD makeup','Hair styling basics','Client consultation & aftercare','Pricing and running a home salon']::text[], '[{"title":"Module 1 — Fundamentals","days":23},{"title":"Module 2 — Core Techniques","days":27},{"title":"Module 3 — Applied Practice","days":23},{"title":"Module 4 — Refinement & Finishing","days":11},{"title":"Module 5 — Business & Portfolio Skills","days":6}]'::jsonb, 'f-deepa', false),
  ('c-9', 'beautician-pro-class-60-days', 'Beautician Pro Class (60 Days)', 'beautician', 'Advanced', 60, 25999, 'Online & offline', 'English, Hindi, Kannada', 4.6, 204, 1876, '60-day beautician certification programme with hands-on practice and an industry-recognised certificate.', 'A structured beautician certification programme covering skin analysis and facial treatments, threading, waxing and hygiene standards, party and hd makeup. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Skin analysis and facial treatments','Threading, waxing and hygiene standards','Party and HD makeup','Hair styling basics','Client consultation & aftercare','Pricing and running a home salon']::text[], '[{"title":"Module 1 — Fundamentals","days":15},{"title":"Module 2 — Core Techniques","days":18},{"title":"Module 3 — Applied Practice","days":15},{"title":"Module 4 — Refinement & Finishing","days":7},{"title":"Module 5 — Business & Portfolio Skills","days":5}]'::jsonb, 'f-deepa', false),
  ('c-10', 'beautician-master-class-30-days', 'Beautician Master Class (30 Days)', 'beautician', 'Master', 30, 9999, 'Online & offline', 'English, Hindi, Kannada', 4.8, 257, 373, '30-day beautician certification programme with hands-on practice and an industry-recognised certificate.', 'A structured beautician certification programme covering skin analysis and facial treatments, threading, waxing and hygiene standards, party and hd makeup. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Skin analysis and facial treatments','Threading, waxing and hygiene standards','Party and HD makeup','Hair styling basics','Client consultation & aftercare','Pricing and running a home salon']::text[], '[{"title":"Module 1 — Fundamentals","days":8},{"title":"Module 2 — Core Techniques","days":9},{"title":"Module 3 — Applied Practice","days":8},{"title":"Module 4 — Refinement & Finishing","days":4},{"title":"Module 5 — Business & Portfolio Skills","days":1}]'::jsonb, 'f-deepa', false),
  ('c-11', 'nail-art-pro-master-90-days', 'Nail Art Pro Master (90 Days)', 'nail-art', 'Advanced', 90, 24999, 'Online & offline', 'English, Hindi, Kannada', 4.5, 310, 570, '90-day nail art programme with hands-on practice and an industry-recognised certificate.', 'A structured nail art programme covering nail prep, shaping and cuticle care, gel polish and extensions, chrome, ombré and hand-painted art. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Nail prep, shaping and cuticle care','Gel polish and extensions','Chrome, ombré and hand-painted art','Tool sterilisation and safety','Speed techniques for salon work','Pricing your first clients']::text[], '[{"title":"Module 1 — Fundamentals","days":23},{"title":"Module 2 — Core Techniques","days":27},{"title":"Module 3 — Applied Practice","days":23},{"title":"Module 4 — Refinement & Finishing","days":11},{"title":"Module 5 — Business & Portfolio Skills","days":6}]'::jsonb, 'f-kavya', false),
  ('c-12', 'nail-art-master-class-45-days', 'Nail Art Master Class (45 Days)', 'nail-art', 'Master', 45, 12999, 'Online & offline', 'English, Hindi, Kannada', 4.7, 363, 767, '45-day nail art programme with hands-on practice and an industry-recognised certificate.', 'A structured nail art programme covering nail prep, shaping and cuticle care, gel polish and extensions, chrome, ombré and hand-painted art. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Nail prep, shaping and cuticle care','Gel polish and extensions','Chrome, ombré and hand-painted art','Tool sterilisation and safety','Speed techniques for salon work','Pricing your first clients']::text[], '[{"title":"Module 1 — Fundamentals","days":11},{"title":"Module 2 — Core Techniques","days":14},{"title":"Module 3 — Applied Practice","days":11},{"title":"Module 4 — Refinement & Finishing","days":5},{"title":"Module 5 — Business & Portfolio Skills","days":4}]'::jsonb, 'f-kavya', false),
  ('c-13', '24-days-nail-art-certification-course', '24 Days Nail Art Certification Course', 'nail-art', 'Certification', 24, 6999, 'Online & offline', 'English, Hindi, Kannada', 4.9, 116, 964, '24-day nail art programme with hands-on practice and an industry-recognised certificate.', 'A structured nail art programme covering nail prep, shaping and cuticle care, gel polish and extensions, chrome, ombré and hand-painted art. Every module has practice assignments graded by faculty.', array['Nail prep, shaping and cuticle care','Gel polish and extensions','Chrome, ombré and hand-painted art','Tool sterilisation and safety','Speed techniques for salon work','Pricing your first clients']::text[], '[{"title":"Module 1 — Fundamentals","days":7},{"title":"Module 2 — Core Techniques","days":7},{"title":"Module 3 — Applied Practice","days":6},{"title":"Module 4 — Refinement & Finishing","days":4}]'::jsonb, 'f-kavya', true),
  ('c-14', 'nail-art-foundation-course-10-days', 'Nail Art Foundation Course (10 Days)', 'nail-art', 'Foundation', 10, 2999, 'Online', 'English, Hindi, Kannada', 4.6, 169, 1161, '10-day nail art programme with hands-on practice and an industry-recognised certificate.', 'A structured nail art programme covering nail prep, shaping and cuticle care, gel polish and extensions, chrome, ombré and hand-painted art. Every module has practice assignments graded by faculty.', array['Nail prep, shaping and cuticle care','Gel polish and extensions','Chrome, ombré and hand-painted art','Tool sterilisation and safety','Speed techniques for salon work','Pricing your first clients']::text[], '[{"title":"Module 1 — Fundamentals","days":3},{"title":"Module 2 — Core Techniques","days":3},{"title":"Module 3 — Applied Practice","days":3},{"title":"Module 4 — Refinement & Finishing","days":1}]'::jsonb, 'f-kavya', false),
  ('c-15', 'nail-art-basic-course-3-days', 'Nail Art Basic Course (3 Days)', 'nail-art', 'Basic', 3, 999, 'Online', 'English, Hindi, Kannada', 4.8, 222, 1358, '3-day nail art programme with hands-on practice and an industry-recognised certificate.', 'A structured nail art programme covering nail prep, shaping and cuticle care, gel polish and extensions, chrome, ombré and hand-painted art. Every module has practice assignments graded by faculty.', array['Nail prep, shaping and cuticle care','Gel polish and extensions','Chrome, ombré and hand-painted art','Tool sterilisation and safety','Speed techniques for salon work','Pricing your first clients']::text[], '[{"title":"Tools, materials & safety","days":1},{"title":"Core techniques","days":1},{"title":"Practice piece & review","days":1}]'::jsonb, 'f-kavya', false),
  ('c-16', 'bridal-mehandi-master-pro-90-days', 'Bridal Mehandi Master Pro (90 Days)', 'mehandi', 'Advanced', 90, 19999, 'Online & offline', 'English, Hindi, Kannada', 4.5, 275, 1555, '90-day mehandi design programme with hands-on practice and an industry-recognised certificate.', 'A structured mehandi design programme covering cone making and paste consistency, traditional and arabic patterns, bridal full-hand and feet layouts. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Cone making and paste consistency','Traditional and Arabic patterns','Bridal full-hand and feet layouts','Dark-stain aftercare advice','Speed techniques for events','Getting bridal bookings']::text[], '[{"title":"Module 1 — Fundamentals","days":23},{"title":"Module 2 — Core Techniques","days":27},{"title":"Module 3 — Applied Practice","days":23},{"title":"Module 4 — Refinement & Finishing","days":11},{"title":"Module 5 — Business & Portfolio Skills","days":6}]'::jsonb, 'f-anjali', true),
  ('c-17', 'mehandi-master-class-45-days', 'Mehandi Master Class (45 Days)', 'mehandi', 'Master', 45, 9999, 'Online & offline', 'English, Hindi, Kannada', 4.7, 328, 1752, '45-day mehandi design programme with hands-on practice and an industry-recognised certificate.', 'A structured mehandi design programme covering cone making and paste consistency, traditional and arabic patterns, bridal full-hand and feet layouts. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Cone making and paste consistency','Traditional and Arabic patterns','Bridal full-hand and feet layouts','Dark-stain aftercare advice','Speed techniques for events','Getting bridal bookings']::text[], '[{"title":"Module 1 — Fundamentals","days":11},{"title":"Module 2 — Core Techniques","days":14},{"title":"Module 3 — Applied Practice","days":11},{"title":"Module 4 — Refinement & Finishing","days":5},{"title":"Module 5 — Business & Portfolio Skills","days":4}]'::jsonb, 'f-anjali', false),
  ('c-18', 'mehandi-foundation-course-14-days', 'Mehandi Foundation Course (14 Days)', 'mehandi', 'Foundation', 14, 3999, 'Online', 'English, Hindi, Kannada', 4.9, 81, 1949, '14-day mehandi design programme with hands-on practice and an industry-recognised certificate.', 'A structured mehandi design programme covering cone making and paste consistency, traditional and arabic patterns, bridal full-hand and feet layouts. Every module has practice assignments graded by faculty.', array['Cone making and paste consistency','Traditional and Arabic patterns','Bridal full-hand and feet layouts','Dark-stain aftercare advice','Speed techniques for events','Getting bridal bookings']::text[], '[{"title":"Module 1 — Fundamentals","days":4},{"title":"Module 2 — Core Techniques","days":4},{"title":"Module 3 — Applied Practice","days":4},{"title":"Module 4 — Refinement & Finishing","days":2}]'::jsonb, 'f-anjali', false),
  ('c-19', 'mehandi-basic-course-3-days', 'Mehandi Basic Course (3 Days)', 'mehandi', 'Basic', 3, 999, 'Online', 'English, Hindi, Kannada', 4.6, 134, 446, '3-day mehandi design programme with hands-on practice and an industry-recognised certificate.', 'A structured mehandi design programme covering cone making and paste consistency, traditional and arabic patterns, bridal full-hand and feet layouts. Every module has practice assignments graded by faculty.', array['Cone making and paste consistency','Traditional and Arabic patterns','Bridal full-hand and feet layouts','Dark-stain aftercare advice','Speed techniques for events','Getting bridal bookings']::text[], '[{"title":"Tools, materials & safety","days":1},{"title":"Core techniques","days":1},{"title":"Practice piece & review","days":1}]'::jsonb, 'f-anjali', false),
  ('c-20', 'embroidery-master-pro-90-days', 'Embroidery Master Pro (90 Days)', 'embroidery', 'Advanced', 90, 19999, 'Online & offline', 'English, Hindi, Kannada', 4.8, 187, 643, '90-day embroidery programme with hands-on practice and an industry-recognised certificate.', 'A structured embroidery programme covering hand embroidery stitches, aari and maggam work, bead, sequin and zardosi finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand embroidery stitches','Aari and maggam work','Bead, sequin and zardosi finishing','Tracing and transferring designs','Blouse and lehenga layouts','Costing custom orders']::text[], '[{"title":"Module 1 — Fundamentals","days":23},{"title":"Module 2 — Core Techniques","days":27},{"title":"Module 3 — Applied Practice","days":23},{"title":"Module 4 — Refinement & Finishing","days":11},{"title":"Module 5 — Business & Portfolio Skills","days":6}]'::jsonb, 'f-radha', true),
  ('c-21', 'embroidery-master-class-45-days', 'Embroidery Master Class (45 Days)', 'embroidery', 'Master', 45, 9999, 'Online & offline', 'English, Hindi, Kannada', 4.5, 240, 840, '45-day embroidery programme with hands-on practice and an industry-recognised certificate.', 'A structured embroidery programme covering hand embroidery stitches, aari and maggam work, bead, sequin and zardosi finishing. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['Hand embroidery stitches','Aari and maggam work','Bead, sequin and zardosi finishing','Tracing and transferring designs','Blouse and lehenga layouts','Costing custom orders']::text[], '[{"title":"Module 1 — Fundamentals","days":11},{"title":"Module 2 — Core Techniques","days":14},{"title":"Module 3 — Applied Practice","days":11},{"title":"Module 4 — Refinement & Finishing","days":5},{"title":"Module 5 — Business & Portfolio Skills","days":4}]'::jsonb, 'f-radha', false),
  ('c-22', 'embroidery-foundation-course-14-days', 'Embroidery Foundation Course (14 Days)', 'embroidery', 'Foundation', 14, 3999, 'Online', 'English, Hindi, Kannada', 4.7, 293, 1037, '14-day embroidery programme with hands-on practice and an industry-recognised certificate.', 'A structured embroidery programme covering hand embroidery stitches, aari and maggam work, bead, sequin and zardosi finishing. Every module has practice assignments graded by faculty.', array['Hand embroidery stitches','Aari and maggam work','Bead, sequin and zardosi finishing','Tracing and transferring designs','Blouse and lehenga layouts','Costing custom orders']::text[], '[{"title":"Module 1 — Fundamentals","days":4},{"title":"Module 2 — Core Techniques","days":4},{"title":"Module 3 — Applied Practice","days":4},{"title":"Module 4 — Refinement & Finishing","days":2}]'::jsonb, 'f-radha', false),
  ('c-23', 'embroidery-basic-course-3-days', 'Embroidery Basic Course (3 Days)', 'embroidery', 'Basic', 3, 999, 'Online', 'English, Hindi, Kannada', 4.9, 346, 1234, '3-day embroidery programme with hands-on practice and an industry-recognised certificate.', 'A structured embroidery programme covering hand embroidery stitches, aari and maggam work, bead, sequin and zardosi finishing. Every module has practice assignments graded by faculty.', array['Hand embroidery stitches','Aari and maggam work','Bead, sequin and zardosi finishing','Tracing and transferring designs','Blouse and lehenga layouts','Costing custom orders']::text[], '[{"title":"Tools, materials & safety","days":1},{"title":"Core techniques","days":1},{"title":"Practice piece & review","days":1}]'::jsonb, 'f-radha', false),
  ('c-24', 'saree-draping-12-styles-42-days', 'Saree Draping: 12 Styles (42 Days)', 'saree-draping', 'Master', 42, 5400, 'Online & offline', 'English, Hindi, Kannada', 4.6, 99, 1431, '42-day saree draping programme with hands-on practice and an industry-recognised certificate.', 'A structured saree draping programme covering 12 regional draping styles, pre-pleating and box-folding, quick event draping under 30 minutes. Every module has practice assignments graded by faculty, and you finish with a portfolio you can show clients.', array['12 regional draping styles','Pre-pleating and box-folding','Quick event draping under 30 minutes','Pinning for comfort and movement','Draping for photo shoots','Building a draping clientele']::text[], '[{"title":"Module 1 — Fundamentals","days":11},{"title":"Module 2 — Core Techniques","days":13},{"title":"Module 3 — Applied Practice","days":11},{"title":"Module 4 — Refinement & Finishing","days":5},{"title":"Module 5 — Business & Portfolio Skills","days":2}]'::jsonb, 'f-meera', true),
  ('c-25', 'saree-draping-basic-course-3-days', 'Saree Draping Basic Course (3 Days)', 'saree-draping', 'Basic', 3, 999, 'Online', 'English, Hindi, Kannada', 4.8, 152, 1628, '3-day saree draping programme with hands-on practice and an industry-recognised certificate.', 'A structured saree draping programme covering 12 regional draping styles, pre-pleating and box-folding, quick event draping under 30 minutes. Every module has practice assignments graded by faculty.', array['12 regional draping styles','Pre-pleating and box-folding','Quick event draping under 30 minutes','Pinning for comfort and movement','Draping for photo shoots','Building a draping clientele']::text[], '[{"title":"Tools, materials & safety","days":1},{"title":"Core techniques","days":1},{"title":"Practice piece & review","days":1}]'::jsonb, 'f-meera', false)
on conflict do nothing;

insert into public.services (id, slug, title, category, initials, summary, description, price_from, duration, sort) values
  ('s-bridal-makeup', 'bridal-makeup', 'Bridal Makeup', 'Beauty', 'BM', 'Professional bridal makeup for weddings, receptions and special occasions.', 'Includes a consultation call, HD base, lashes and a finish that lasts through the ceremony and photos.', 2500, '2–3 hours', 0),
  ('s-nail-art', 'nail-art', 'Nail Art', 'Beauty', 'NA', 'Clean, detailed nail art for everyday looks, events and celebrations.', 'Gel, chrome and hand-painted sets at a partner studio or at your home.', 800, '1–2 hours', 1),
  ('s-beautician', 'beautician-at-home', 'Beautician at Home', 'Beauty', 'BE', 'Beauty care and grooming delivered by trained professionals.', 'Facials, threading, waxing and clean-ups at your home with salon-grade hygiene.', 500, '1–2 hours', 2),
  ('s-mehndi-occasions', 'mehndi-for-occasions', 'Mehndi for Occasions', 'Art & Craft', 'MO', 'Traditional and contemporary mehndi for festivals, parties and celebrations.', 'Quick, elegant designs for festivals, sangeet and family functions.', 500, '1–3 hours', 3),
  ('s-bridal-mehndi', 'bridal-mehndi', 'Bridal Mehndi', 'Art & Craft', 'BH', 'Detailed bridal mehndi designs for hands and feet, customised for your occasion.', 'Traditional and modern bridal designs, timed around your muhurtam, with dark-stain aftercare guidance.', 4500, '3–5 hours', 4),
  ('s-saree-draping', 'saree-draping', 'Saree Draping', 'Fashion', 'SD', 'Elegant saree draping for weddings, functions, shoots and special events.', 'Pre-pleated or freehand draping in 12 regional styles, done in under 30 minutes.', 900, '30–45 min', 5),
  ('s-blouse-stitching', 'blouse-stitching', 'Blouse Stitching', 'Tailoring', 'BS', 'Custom-fit blouses with designer necks and sleeves.', 'Measurements at home or studio, one trial fitting, delivered in 5–7 days.', 1200, '5–7 days', 6),
  ('s-aari-embroidery', 'aari-embroidery', 'Aari Embroidery', 'Tailoring', 'AE', 'Hand aari and maggam work on blouses, lehengas and dupattas.', 'Custom motifs traced to your outfit, with bead and zardosi finishing.', 1800, '7–10 days', 7)
on conflict do nothing;

insert into public.professionals (id, slug, name, initials, title, city, rating, bookings_count, service_ids, bio, verified) values
  ('p-ananya', 'ananya-makeup-studio', 'Ananya Makeup Studio', 'AM', 'Bridal makeup artist', 'Bengaluru', 4.9, 120, array['s-bridal-makeup']::text[], 'Syllabdosth-certified bridal artist specialising in HD and airbrush makeup.', true),
  ('p-priya', 'priya-mehndi-arts', 'Priya Mehndi Arts', 'PM', 'Mehndi artist', 'Bengaluru', 4.8, 210, array['s-bridal-mehndi','s-mehndi-occasions']::text[], 'Bridal and Arabic mehndi, known for fine detailing and dark stains.', true),
  ('p-lavanya', 'lavanya-beauty-studio', 'Lavanya Beauty Studio', 'LB', 'Beautician', 'Bengaluru', 4.9, 120, array['s-beautician']::text[], 'At-home facials and grooming with salon-grade hygiene.', true),
  ('p-meera', 'meera-nail-lounge', 'Meera Nail Lounge', 'MN', 'Nail artist', 'Bengaluru', 4.7, 95, array['s-nail-art']::text[], 'Gel, chrome and hand-painted sets at studio or home.', true),
  ('p-kavya', 'kavya-drapes', 'Kavya Drapes', 'KD', 'Saree draping artist', 'Bengaluru', 4.9, 160, array['s-saree-draping']::text[], 'Drapes for weddings and shoots in 12 regional styles.', true),
  ('p-lakshmi', 'lakshmi-tailoring', 'Lakshmi Tailoring', 'LT', 'Tailor & embroiderer', 'Bengaluru', 4.8, 140, array['s-blouse-stitching','s-aari-embroidery']::text[], 'Designer blouses and aari work with one trial fitting.', true)
on conflict do nothing;

insert into public.blog_posts (slug, title, category, author, read_mins, published_at, excerpt, intro, sections, quote) values
  ('turn-mehandi-hobby-into-business', 'How to turn a mehandi hobby into a full-time business', 'Career', 'Anjali R.', 6, '2026-08-12', 'From your first paid booking to a full wedding season — what actually works.', 'Most of our mehandi graduates start with family functions. The ones who go full-time do three things differently.', '[{"heading":"1. Build a portfolio before you charge","text":"Photograph every design in natural light, front and back of the hand. Twenty strong photos beat a hundred average ones."},{"heading":"2. Price by the hour, quote by the event","text":"Know your hourly number, then quote clients a single event price. It is easier for them to say yes."},{"heading":"3. Get listed where brides search","text":"Certified graduates can join the Syllabdosth professional network and receive booking requests directly."}]'::jsonb, 'Your first ten clients come from people who already know you. Your next hundred come from your portfolio.'),
  ('saree-draping-styles-wedding-season', '5 saree draping styles to know this wedding season', 'Trends', 'Meera T.', 4, '2026-09-02', 'The drapes clients are asking for most — and when to suggest each one.', 'Wedding season brings every kind of request. These five drapes cover most of them.', '[{"heading":"1. Classic Nivi drape","text":"Clean pleats and a neat pallu. Works with almost every fabric and is the safest choice for long ceremonies."},{"heading":"2. Gujarati seedha pallu","text":"The pallu comes to the front to show off heavy borders and embroidery."},{"heading":"3. Bengali-inspired drape","text":"A distinctive silhouette with broad pleats. Works well when you want a more traditional statement."},{"heading":"4. Contemporary open-pallu style","text":"A lighter, modern look that keeps the details of the saree visible."},{"heading":"5. Pre-pleated or structured drape","text":"For busy wedding days, a pre-pleated drape makes getting ready faster and keeps the look neat all day."}]'::jsonb, 'The best saree drape is one that complements the fabric, occasion and comfort of the person wearing it.'),
  ('nail-art-certification-worth-it', 'What actually makes a nail art certification worth it', 'Certification', 'Kavya S.', 5, '2026-09-18', 'Five questions to ask before you pay for any nail art course.', 'Not every certificate helps you get clients. Here is what to look for.', '[{"heading":"Is there graded practice?","text":"You should be assessed on real sets, not just attendance."},{"heading":"Does it teach hygiene properly?","text":"Sterilisation and safe product use protect your clients and your reputation."},{"heading":"Does it lead to work?","text":"Look for courses that connect you with paying clients after you graduate."}]'::jsonb, null)
on conflict do nothing;

-- After you sign up with your own account, make yourself admin:
-- update public.profiles set role = 'admin' where email = 'you@example.com';
-- Link a professional or faculty listing to a user account:
-- update public.professionals set user_id = (select id from public.profiles where email = 'ananya@example.com') where slug = 'ananya-makeup-studio';
